<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/* 
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */

$config['query_string_segment'] = 'start';

$config['full_tag_open'] = '<aside class="pagination devider-top devider-heavy devider-margin-medium"><ul>';
$config['full_tag_close'] = '</ul></aside><!-- .pagination -->';

$config['first_link'] = 'First';
$config['first_tag_open'] = '<li class="prev">';
$config['first_tag_close'] = '</li>';

$config['last_link'] = 'Last';
$config['last_tag_open'] = '<li class="next">';
$config['last_tag_close'] = '</li>';

$config['next_link'] = 'Next';
$config['next_tag_open'] = '<li class="next">';
$config['next_tag_close'] = '</li>';

$config['prev_link'] = 'Prev';
$config['prev_tag_open'] = '<li class="prev">';
$config['prev_tag_close'] = '</li>';

$config['cur_tag_open'] = '<li class="current">Page<br/>- ';
$config['cur_tag_close'] = ' -</li>';

$config['num_tag_open'] = '';
$config['num_tag_close'] = '';



/*
$config['query_string_segment'] = 'start';

$config['full_tag_open'] = '<aside class="pagination devider-top devider-heavy devider-margin-medium"><ul>';
$config['full_tag_close'] = '</ul></aside><!-- .pagination -->';

$config['first_link'] = 'First';
$config['first_tag_open'] = '<li class="prev">';
$config['first_tag_close'] = '</li>';

$config['last_link'] = 'Last';
$config['last_tag_open'] = '<li class="next">';
$config['last_tag_close'] = '</li>';

$config['next_link'] = 'Next';
$config['next_tag_open'] = '<li class="next">';
$config['next_tag_close'] = '</li>';

$config['prev_link'] = 'Prev';
$config['prev_tag_open'] = '<li class="prev">';
$config['prev_tag_close'] = '</li>';

$config['cur_tag_open'] = '<li class="current">Page<br/>- ';
$config['cur_tag_close'] = ' -</li>';

$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';










$config['full_tag_open'] = '<div class="pagination"><ul>';
$config['full_tag_close'] = '</ul></div>';
 
$config['first_link'] = '&laquo; First';
$config['first_tag_open'] = '<li class="prev page">';
$config['first_tag_close'] = '</li>';
 
$config['last_link'] = 'Last &raquo;';
$config['last_tag_open'] = '<li class="next page">';
$config['last_tag_close'] = '</li>';
 
$config['next_link'] = 'Next &rarr;';
$config['next_tag_open'] = '<li class="next page">';
$config['next_tag_close'] = '</li>';
 
$config['prev_link'] = '&larr; Previous';
$config['prev_tag_open'] = '<li class="prev page">';
$config['prev_tag_close'] = '</li>';
 
$config['cur_tag_open'] = '<li class="active"><a href="">';
$config['cur_tag_close'] = '</a></li>';
 
$config['num_tag_open'] = '<li class="page">';
$config['num_tag_close'] = '</li>';
*/


/*
<a>
</a>
//berfungsi untuk melampirkan markup
  $config['full_tag_open'] = '<ul>';
  $config['full_tag_close'] = '</ul>';
  
  //berfungsi untuk Menyesuaikan "first" Link
  $config['first_link'] = '« First';
  $config['first_tag_open'] = '<li><span aria-hidden="true"><i class="fa fa-chevron-left"></i>';
  $config['first_tag_close'] = '</span></li>';
  
  //berfungsi untuk Menyesuaikan Link terakhir
  $config['last_link'] = 'Last »';
  $config['last_tag_open'] = '<li><span aria-hidden="true">';
  $config['last_tag_close'] = '<i class="fa fa-chevron-right"></i></span></li>';
  
  //berfungsi untuk Menyesuaikan "next" Link
  $config['next_link'] = 'Next <i class="fa fa-chevron-right"></i>';
  $config['next_tag_open'] = '<li>';
  $config['next_tag_close'] = '</li>';
  
  //berfungsi untuk Menyesuaikan "previous" Link
  $config['prev_link'] = '<i class="fa fa-chevron-left"></i> Previous';
  $config['prev_tag_open'] = '<li>';
  $config['prev_tag_close'] = '</li>';
  
  //berfungsi untuk Menyesuaikan "Current Page" Link
  $config['cur_tag_open'] = '<li><a href="">';
  $config['cur_tag_close'] = '</a></li>';
  
  //berfungsi untuk Menyesuaikan "digit angka" Link
  $config['num_tag_open'] = '<li>';
  $config['num_tag_close'] = '</li>';
*/


/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-01-27 14:08:27 */
/* http://harviacode.com */